export const Colors = {
     light: {
          text: "#000000",
          headings: "#2222FF",
          background: "#FFFFFF",
          buttonsBg: "#2222FF",
          buttonTxt: "#FFFFFF",
          mainIcons: "#FFFFFF",
          mainIconsBg: "#2222FF",
          icons: "#111111",
          links: "#2222FF",
          formInputsPlaceholders: "#AAAAAA",
          formInputsTxt: "#777777",
          formInputsBorder: "#AAAAAA",
          formInputsBg: "#FFFFFF",
     },
     dark: {
          text: "#FFFFFF",
          headings: "#0055FF",
          background: "#000011",
          buttonsBg: "#0055FF",
          buttonTxt: "#FFFFFF",
          mainIcons: "#FFFFFF",
          mainIconsBg: "#0055FF",
          icons: "#FFFFFF",
          links: "#0055FF",
          formInputsPlaceholders: "#777777",
          formInputsTxt: "#BBBBBB",
          formInputsBorder: "#777777",
          formInputsBg: "#000011",
     },
};
