export const Colors = {
  light: {
    text: "#000000",
    headings: "#2222FF",
    background: "#FFFFFF",
    buttonsBg: "#2222FF",
    buttonTxt: "#FFFFFF",
    mainIcons: "#FFFFFF",
    mainIconsBg: "#2222FF",
    icons: "#111111",
    links: "#2222FF",
    formInputsPlaceholders: "#AAAAAA",
    formInputsTxt: "#BBBBBB",
    formInputsBorder: "#AAAAAA",
    formInputsBg: "#FFFFFF",
  },
  dark: {
    text: "#FFFFFF",
    headings: "#0055FF",
    background: "#000022",
    buttonsBg: "#0055FF",
    buttonTxt: "#FFFFFF",
    mainIcons: "#FFFFFF",
    mainIconsBg: "#0055FF",
    icons: "#FFFFFF",
    links: "#0055FF",
    formInputsPlaceholders: "#777777",
    formInputsTxt: "#888888",
    formInputsBorder: "#777777",
    formInputsBg: "#000022",
  },
};
