export const Colors = {
     light: {
          mainColor: "#FFB300",
          headerStartBg: { first: "#111", second: "#111", third: "#111" },
          mainHeaderColor: "#111",
          textColor: "#111",
          secondTextColor: "#111",
          linkColor: "#FFB300",
          mainIconColor: "#111",
          secondIconColor: "#FFF",
          mainRadius: 5,
          sideRadius: 30,
          background: { first: "#CCCCFF", second: "#DDDDFFcc", third: "#EEEEFFaa" },
          footerBg: "#222",
     },
     dark: {
          mainColor: "#55FFFF",
          headerStartBg: { first: "#212F42", second: "#333F60", third: "#454F66" },
          mainHeaderColor: "#333F55",
          textColor: "#FFF",
          secondTextColor: "#FFF",
          linkColor: "#55FFFF",
          mainIconColor: "#EEE",
          secondIconColor: "#333F55",
          mainRadius: 20,
          sideRadius: 30,
          background: { first: "#212F42", second: "#333F60", third: "#454F66" },
          footerBg: "#333F55",
     },
     custom: {
          mainColor: "#440066",
          headerStartBg: { first: "#330055", second: "#440088", third: "#660099" },
          mainHeaderColor: "#441166",
          textColor: "#FFF",
          secondTextColor: "#111",
          linkColor: "#440066",
          mainIconColor: "#666",
          secondIconColor: "#999",
          mainRadius: 10,
          sideRadius: 30,
          background: { first: "#EEE", second: "#FFF", third: "#DDD" },
          // background: { first: "#330055", second: "#440088", third: "#660099" },
          footerBg: "#441166",
     }
};
